name: dockerhub-push

on:
  push:
    branches: [ "main" ]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains a single job called "push_to_registry"
  push_to_registry:
    name: push docker image to docker hub
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: checkout the repository
        uses: actions/checkout@v3

      # login into docker hub
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build the docker image then push it to docker hub
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cxtechnology/tictacgo:latest
